query hotel($language: String!, $ctyhocn: String!) {
    hotel(ctyhocn: $ctyhocn, language: $language) {
      ctyhocn
      brandCode
      name
      status
      rewardCategory
      yearBuilt
      yearLastRenovated
      leadRate {
        lowest {
          rateAmount(currencyCode: "AUD")
        }
      }
      creditCardTypes{
        name
      }
      address{
        addressLine1
        addressLine2
        addressLine3
        city
        state
        postalCode
      }
      contactInfo{
        phoneNumber
        emailAddress1
        emailAddress2
      }
      roomTypeCategories{
        category
      }
      roomTypes{
        roomTypeName
        numBeds
        smokingRoom
        features{
          name
        }
      }
      internetAccess{
        hasGuestHSIA
        hasWlanInRoom
        hasWlanPublic
        hasFreeGuestHSIA
        inRoomHSIAFee
      }
      capabilities{
        digitalCheckIn
        digitalKey
        digitalKeyShare
        digitalKeyParking
        digitalKeyPassiveUnlock
      }
      amenities{
        id
        name
      }
      serviceAmenities{
        name
      }
      foodAndBeverage{
        hasOnSiteRestaurant
        numberOfRestaurants
        hasKidsMenu
        hasHighChairs
        hasRoomService
        hasBrailleMenus
        hasFreeBreakfast
        breakfastType
        numberOfBars
        beverageDescription
        complimentaryBeverageOffered
        has24HourRoomService
        complimentaryBreakfastOffered
        restaurantDetails{
          _id
          name
        }
      }
      fitnessAndRecreation{
        hasGolfCourse
        hasExerciseRoom
        hasTennisCourt
        hasFitnessCenter
        hasBarbequeGrills
        hasNearbyGolfCourse
        hasCarpetTennisCourt
        recreationServices{
          type
        }
      }
      pools{
        totalNumberOfSwimmingPools
        hasIndoorPool
        hasOutdoorPool
        hasWhirlpool
        hasPoolsideCabanas
        hasSwimmingPoolHoistForPoolAccess
      }
      parking{
        hasFreeParking
        hasSelfParking
        hasValetParking
        hasOnsiteParking
        hasOnSiteParking
        hasCoveredParking
        hasSecuredParking
        hasParkingFacility
        hasAccessGateParking
        hasAccessibleParking
        hasInOutParkingPrivilege
        vanAccessibleParking
        evCharging{
          hasChargingOnsite
          hasChargingNearby
          chargingUnitDistance
        }
      }
      airports{
        name
        distance
        driveTimeFmt
      }
      pets{
        petsAllowed
        petCharge
        petMaxSize
        petMaxWeight{
          amount
        }
        servicePetsAllowed
        petChargeRefundable
      }
      meetingRooms{
        name
        ceilingHeight
        width
        length
        area
        isForExhibitUse
        typeDesc
        locationDesc
        isOffSite
        configurationCapacities{
          banquet
          classroom
          hollowSquare
          tabletopBooths
        }
      }
  }
}